### ISSUE TITLE
Add direct linking to implicit functions (and expose them)

### ISSUE THREAD

**Issue by rexagod** [publiclab/matcher-core#10]
> The findMatchedPoints function doesn't take any values explicity, those are served to it owing to the findPoints method.

Hm, why doesn't it accept two `points` parameters, between which it finds matches? Wouldn't that make more sense to a user? Like, it would take two points collections as inputs, and output those which are matched between? If this would take extra changes, let's do that in a follow-up PR. Can you open an issue and copy these notes in? Thanks!

> The function, however, depends specifically on args.browser that's initialized all the way at the top. Do you want me to highlight this?

Yes, that doesn't seem so clear to me so it may need explaining. 

So, `Below is a summary of each component of the orbify instance` doesn't clearly spell out that these are parameters that can be submitted in the constructor. I think it's very important to literally show verbatim how to use each of the constructors, as in this example:

![image](https://user-images.githubusercontent.com/24359/61965267-cc127a00-af9d-11e9-8b16-1aef881b067f.png)

That'll make it much easier for people to start using this library, or to use it in unexpected ways! 

Thank you, @rexagod -- much appreciated!

_Originally posted by @jywarren in https://github.com/publiclab/matcher-core/pull/6_

**Comment by jywarren** [comment]
Looks great, thanks!

**Comment by rexagod** [comment]
Closed since `query` api was exposed allowing users to run these functions differently.

https://github.com/publiclab/matcher-core/blob/main/README.md#arguments
