### ISSUE TITLE
Add online demo in gh-pages

### ISSUE THREAD

**Issue by jywarren** [publiclab/matcher-core#14]
This can be something really simple, which:

1. shows 2 images in an html page
2. has a button that says "find points"
3. displays "100 points found in image A" and "100 points found in image B" or equivalent on completion
4. has a second button that says "find matches"
5. displays "20 matches found" on completion
6. has a third button that says "suggest projection"
7. uses CSS rotate and absolute-positioning to roughly overlay the 2nd image onto the first (i guess?)

This will provide a substantial guide to how to implement #5 and #11 

Thanks!

**Comment by rexagod** [comment]
@jywarren I've rendered the above factors and made some changes to the projection idea [on the gh-pages deployment](https://publiclab.github.io/matcher-core/).

I've actually tried to show each matched point in one image wrt the other but overlapping them would have made it seem less discernable and while core actually "matches" the images, overlapping or "stitching" the images would result in images overlapped but shifted over each other (as you've seen in the sticher module) so I was unsure if that's what we needed here. However, if you want to show the stitching part in this as an example, we can probably drop a link of the LDI gh pages after merging the core into it?

**Comment by jywarren** [comment]
This looks awesome! Wouldn't it be better to use two images of actually the
same thing, not just 2 sunflowers? Like, two images that overlap from say
https://mapknitter.org/maps/ceres--2/

https://s3.amazonaws.com/grassrootsmapping/warpables/306187/DJI_1207.JPG
 and
https://s3.amazonaws.com/grassrootsmapping/warpables/306188/DJI_1205.JPG

(maybe scaled down?)

This is a fantastic demo! Great work!

I think the stitcher/projector isn't urgent to show in the demo here. We
can, but there are plenty of other things to prioritize as well. Thanks!

**Comment by rexagod** [comment]
@jywarren No need to downscale, core's inner mechanisms will take care of that. For the images above, I've redesigned the demo, so let me know what you think! Thanks!

**Comment by jywarren** [comment]
it's amazing. i love it!

Let's meet up in
https://github.com/publiclab/Leaflet.DistortableImage/pull/312 and
https://github.com/publiclab/image-sequencer/pull/1198 for next steps, then?

**Comment by rexagod** [comment]
Sure thing! Closing this one now.
