### ISSUE TITLE
Is a simpler constructor possible?

### ISSUE THREAD

**Issue by jywarren** [publiclab/matcher-core#3]
This is very cool!

```js

// Resolving the returned values
Promise.resolve(new orbify('/path/to/img1.jpg', '/path/to/img2.jpg', {
	browser: true,	// required for browser (non-node) environments
	params: {
		lap_thres: 35,
		eigen_thres: 40,
		blur_size: 4,
		matchThreshold: 50
	}
}).utils).then(function (utils) {
	callback(utils);	// passing resolved value to callback's scope
});
```

Would it be possible to wrap this in a simpler constructor like:

```js
var matcher = Matcher.new(
  '/path/to/img1.jpg', 
  '/path/to/img2.jpg',
  callbackFn,
  options
)
```

Which runs `callbackFn(response)` where `response` is `{matches: Array(9), corners: Array(500)}` ?

(is that right?)

Would there be disadvantages to a simpler syntax like this which wraps the promises?

**Comment by rexagod** [comment]
@jywarren Considering the aforementioned case where `response` would be the resolved value of the `Promise` we are returning currently, this would mean _asynchronously_ resolving the `Promise` in the same file we are resolving it, which will lead to increased load times, not to mention this practice (same-scope-resolution) doesn't feel right from a semantic POV, as it can lead to less readability from a newcomers' perspective.

What I can think of right now though, in an effort to simplify the constructor, is employ `await` for constructor initialization, the main advantage here being that we won't have to pass this into a limited scope, but rather use it's instance as the namespace in the same scope, thus more convenient.

Like this.

```js
<script>
const utils = async () => await new Orbify('./assets/resources/small.jpg', './assets/resources/big.jpg', {option1: value1, option2: value2}).utils;
// access utils globally!
</script>
```

So let me know if the above format looks good to go, or if you think we should make this even more simpler (although that may lead to delays).

**Comment by rexagod** [comment]
@jywarren Is this okay?

```html
<script>

  new Matcher('../assets/resources/small.jpg', '../assets/resources/small.jpg',
  async function (r) {
    document.getElementById('res').innerHTML = JSON.stringify(await r);
  }, {
      browser: true,
      caching: true,
      leniency: 30,
      params: {
        lap_thres: 30,
        eigen_thres: 35
      }
    });

</script>
```

**Comment by rexagod** [comment]
The signature of the above constructor is, `new Matcher('pathA', 'pathB', callback, options)` similar to your specification above.

**Comment by jywarren** [comment]
Yes, that is much better! However we can still refine a bit, i think:

```js
<script>

  new Matcher('../assets/resources/small.jpg', '../assets/resources/small.jpg',
  async function onMatchComplete(r) {
    // a comment describing what we're doing on the next line:
    document.getElementById('res').innerHTML = JSON.stringify(await r);
  }, {
      browser: true,
      cache_matches: true, // stores matches in _______ 
      leniency: 30,
      params: {
        lap_thres: 30,
        eigen_thres: 35
      }
    });
</script>
```

Here, i also sought to explain what is cached and where (like, local storage, in memory only, where is the cache actually kept?)! Does that make sense?

Thanks!!! And the additional documentation below this in the README could detail the specific parameters. 

This is gonna be SUPER!

**Comment by jywarren** [comment]
And, which of these parameters are optional?

**Comment by jywarren** [comment]
Hi, @rexagod can you provide an update here? Thanks!

**Comment by rexagod** [comment]
Hi, @jywarren! The comments would be really helpful to users to describe what the options mean, I'll add those. For the parameters, at the moment, the I've kept the images and callback to be mandatory for the user to pass in, what do think? Should I make any changes to these as well? Thanks!

**Comment by jywarren** [comment]
Sounds great, thanks!!

**Comment by jywarren** [comment]
Hi @rexagod -- can you please show a PR which encapsulates all the changes relevant to this issue? I see you've changed the demo in 
92d54fd but I don't see the README changes connected there. Please add a README section and link to your commit from here as well! 

Grouping your commits into a PR allows others like myself to see how your changes as a collection of commits have fulfilled the issue -- can you do this in the future? Thank you!

**Comment by rexagod** [comment]
@jywarren Please have a look at https://github.com/publiclab/matcher-core/blob/main/README.md#setup where I've stated the constructor signatures for both environments.

Thanks!

**Comment by rexagod** [comment]
Closing this in favor of the above comment. Feel free to reopen! Thanks!
